company/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import (
    company_home,
    company_profile,
    company_jobs,
    company_create_job,
    company_update_job,
    company_delete_job,
    accepted_status,
    hired_status,
    delete_request,
    reject_and_delete_request,
    job_candidates_view,
)


urlpatterns = [
    path("home", company_home, name="company-home"),
    path("profile/", company_profile, name="company-profile"),
    path("jobs/", company_jobs, name="company-jobs"),
    path("create/job/", company_create_job, name="company-create-job"),
    path("job/<slug:slug>/update/", company_update_job, name="company-update-job"),
    path("job/<slug:slug>/delete/", company_delete_job, name="company-delete-job"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("accept/request/<int:request_id>/<slug:slug>/", accepted_status, name="accept-status"),
    path("hire/request/<int:request_id>/<slug:slug>/", hired_status, name="hire-status"),
    path("delete/request/<int:request_id>/<slug:slug>/", delete_request, name="delete-request"),
    path(
        "reject-and-delete/request/<int:request_id>/<slug:slug>/",
        reject_and_delete_request,
        name="reject-and-delete-request",
    ),
    path("job/<slug:slug>/candidates/", job_candidates_view, name='job-candidates'),
]

ujobsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import (
    register,
    login_request,
    home_page,
    job_detail,
    search,
)


urlpatterns = [
    path("", home_page, name="home-page"),
    path("admin/", admin.site.urls),
    path("candidate/", include("candidate.urls")),
    path("company/", include("company.urls")),
    path("register/", register, name="register"),
    path("login/", login_request, name="login"),
    path("job/<slug:slug>/", job_detail, name="job-detail"),
    path("search/", search, name="search"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.utils import timezone
from django.db import models
from core.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Company(models.Model):
    company = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    company_introduction = models.TextField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Company, self).save(*args, **kwargs)


class Job(models.Model):
    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name="jobs",
    )

    title = models.CharField(max_length=80)
    location = models.CharField(max_length=80)

    created_date = models.DateTimeField(default=timezone.now, blank=True)

    experience_choices = (
        ("no_matter", "Não importa"),
        ("1_to_3", "De 1 a 3 anos"),
        ("3_to_6", "De 3 a 6 anos"),
        ("above_6", "Acima de 6 anos"),
    )
    experience = models.CharField(max_length=80, choices=experience_choices)

    salary_choices = (
        ("agreement", "A combinar"),
        ("up_to_1000", "Até 1.000"),
        ("from_1000_to_2000", "De 1.000 a 2.000"),
        ("from_2000_to_3000", "De 2.000 a 3.000"),
        ("above_3000", "Acima de 3.000"),
    )
    salary = models.CharField(max_length=80, choices=salary_choices)

    hiring_choices = (
        ("full_time", "Período integral"),
        ("part_time", "Meio período"),
        ("remote", "Trabalho remoto"),
        ("internship", "Estágio"),
    )
    hiring_type = models.CharField(
        max_length=80,
        choices=hiring_choices,
    )

    job_description = models.TextField()
    skills_required = models.CharField(max_length=120)
    benefits = models.CharField(max_length=120)

    education_choices = (
        ("no_matter", "Não importa"),
        ("elementary_school", "Ensino Fundamental"),
        ("high_school", "Ensino Médio"),
        ("technical_degree", "Tecnólogo"),
        ("undergraduate", "Ensino Superior"),
        ("postgraduate", "Pós / MBA / Mestrado"),
        ("doctorate", "Doutorado"),
    )

    education = models.CharField(max_length=80, choices=education_choices)

    # Campo para armazenar o slug
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.title


# Função para gerar um slug automaticamente
@receiver(pre_save, sender=Job)
def pre_save_job(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)


class JobRequests(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    candidate = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    resume_url = models.CharField(max_length=100)
    accepted = models.BooleanField(default=False)
    hired = models.BooleanField(default=False)
    viewed = models.BooleanField(default=False)
    status = models.CharField(max_length=80, default="Pendente")

    def __str__(self):
        return f"{self.candidate} requested on {self.job}"

    def save(self, *args, **kwargs):
        super(JobRequests, self).save(*args, **kwargs)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from core.managers import MyUserManager


class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    full_name = models.CharField(max_length=100)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_candidate = models.BooleanField(default=True)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["full_name"]

    def __str__(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class UserRegisterForm(UserCreationForm):
    register_choices = (
        ("default", "Selecione uma opção"),
        ("candidate", "Candidato"),
        ("company", "Recrutador"),
    )
    register_as = forms.ChoiceField(
        label="Cadastrar como",
        choices=register_choices,
        widget=forms.Select(
            attrs={"id": "select-style", "autofocus": "autofocus"},
        ),
    )

    full_name = forms.CharField(
        label="Nome completo",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Ex. José Uchôa",
            }
        ),
    )

    email = forms.EmailField(
        label="Informe seu e-mail",
        widget=forms.EmailInput(
            attrs={"placeholder": "Digite seu e-mail"},
        ),
    )

    password1 = forms.CharField(
        label="Definir senha",
        widget=forms.PasswordInput(attrs={"placeholder": "Digite sua senha"}),
    )

    password2 = forms.CharField(
        label="Confirmar senha",
        widget=forms.PasswordInput(attrs={"placeholder": "Repita sua senha"}),
    )

    error_messages = {
        "password_mismatch": "As senhas não correspondem, tente novamente",
    }

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Este e-mail já está sendo usado")
        return email

    class Meta:
        model = User
        fields = [
            "register_as",
            "full_name",
            "email",
            "password1",
            "password2",
        ]


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        label="Informe seu e-mail",
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Digite seu e-mail",
                "autofocus": "autofocus",
            },
        ),
    )
    password = forms.CharField(
        label="Agora, informe sua senha",
        widget=forms.PasswordInput(attrs={"placeholder": "Digite sua senha"}),
    )

core/views.py
from datetime import datetime, timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.http import Http404
from django.db.models import Q

from company.models import Job
from .models import User
from .forms import UserRegisterForm, UserLoginForm


def home_page(request):
    jobs = Job.objects.order_by("-created_date").all()
    # convert time
    now = datetime.now(timezone.utc)
    for i in jobs:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f"{get_days.days} dias atrás"
    return render(request, "home_page.html", {"jobs": jobs})


def job_detail(request, slug):
    job = get_object_or_404(Job, slug=slug)
    return render(request, "job_detail.html", {"job": job})


def register(request):
    if request.user.is_authenticated:
        raise Http404

    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            # Verificar se a opção selecionada é "default"
            if data["register_as"] == "default":
                messages.error(
                    request,
                    'Selecione uma opção válida no campo "Cadastrar como"',
                )
            else:
                user = User.objects.create_user(
                    data["email"],
                    data["full_name"],
                    data["password1"],
                )

                # Determine a rota de redirecionamento com base na
                # seleção do campo "register_as"
                if data["register_as"] == "candidate":
                    user.is_candidate = True
                    user.is_company = False
                elif data["register_as"] == "company":
                    user.is_candidate = False
                    user.is_company = True
                user.save()

                messages.success(
                    request,
                    "Cadastro realizado com sucesso, faça login!",
                )
                return redirect("login")  # Redirecionar para a rota de login
    else:
        form = UserRegisterForm()

    # Se chegamos aqui, ocorreu uma validação mal-sucedida,
    # mas reutilizamos o formulário com os dados submetidos
    return render(request, "register.html", {"form": form})


def login_request(request):
    if request.user.is_authenticated:
        raise Http404
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request,
                email=data["email"],
                password=data["password"],
            )
            if user is not None:
                login(request, user)
                # if user is candidate
                if user.is_candidate:
                    # Verificar se o candidato tem currículo associado
                    profile = getattr(user, "profile", None)
                    if profile and profile.resume:
                        return redirect("home-page")
                    else:
                        messages.info(request, "Por favor, cadastre seu currículo.")
                        return redirect("candidate-profile")
                # if user is a company
                elif not user.is_candidate:
                    return redirect("company-jobs")
            else:
                messages.error(request, "Nome de usuário ou senha incorretos")
                return redirect("login")
    form = UserLoginForm()
    return render(request, "login.html", {"form": form})


def search(request):
    query = request.GET.get("q")
    results = Job.objects.filter(
        Q(title__icontains=query) | Q(skills_required__icontains=query)
    ).all()

    if not results:
        messages.error(request, "Nenhum resultado encontrado")
        return redirect("home-page")
    else:
        messages.success(request, f"{results.count()} resultados encontrados")

    now = datetime.now(timezone.utc)
    for i in results:
        get_days = now - i.created_date
        if get_days.days > 1:
            i.created_date = f"{get_days.days} dias atrás"
    return render(request, "home_page.html", {"jobs": results})

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <!-- Required meta tags -->
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- Bootstrap CSS -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous"
        />

        <!-- Blog CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />

        <!-- Boxicons -->
        <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />

        {% if title %}
        <title>{{ title }}</title>
        {% else %}
        <title>Portal de Emprego Online</title>
        {% endif %}
    </head>

    <body>
        <!-- Navbar -->
        <header>
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <!-- Navbar Brand (on the left) -->
                    <a class="navbar-brand mr-4 ml-2" href="{% url 'home-page' %}">ujobs</a>
                    <!-- Navbar Toggler (for responsive behavior) -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Navbar Links (on the right) -->
                    <div class="collapse navbar-collapse justify-content-end" id="navbarToggle">
                        <ul class="navbar-nav">
                            {% if user.is_authenticated %}
                                {% if not user.is_candidate %}
                                    {% if user.company.jobs %}
                                        <li class="nav-item">
                                            <a class="nav-link active" href="{% url 'company-jobs' %}">Minhas Vagas</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'company-create-job' %}">Publicar Vaga</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'company-home' %}">Currículos Aceitos</a>
                                        </li>
                                    {% endif %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'company-profile' %}">Perfil</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link d-flex" href="{% url 'logout' %}">Sair <i class='bx bx-log-out'></i></a>
                                    </li>
                                {% else %}
                                    {% if user.profile.resume %}
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'candidate-requests' %}">Minhas Candidaturas</a>
                                        </li>
                                    {% else %}
                                        <style>
                                            .navbar-brand {
                                                pointer-events: none !important;
                                            }
                                        </style>
                                    {% endif %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'candidate-profile' %}">Perfil</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link d-flex" href="{% url 'logout' %}">Sair <i class='bx bx-log-out'></i></a>
                                    </li>
                                {% endif %}
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'register' %}">Cadastro</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'login' %}">Entrar</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>            
        </header>
        <main role="main" class="container pt-1">
            {% if request.path != '/login/' and request.path != '/register/' %} {% if messages %} {% for message in messages %}
            <div class="col-md-10 mx-auto alert alert-{{ message.tags }}" style="text-align: center; border-radius: 6px">
                {{ message }}
            </div>
            {% endfor %} {% endif %} {% endif %}

            <!-- search form -->
            {% if request.path == '/' %}
            <div class="content-section col-md-10 mx-auto text-center" style="border-radius: 6px; background-color: #343a40">
                <legend class="mb-4 mt-4" style="color: #fff">Explore o site de vagas de emprego mais completo do Brasil!</legend>
                <div class="mx-auto mb-4" style="max-width: 70%; border-radius: 6px; padding: 2rem; background-color: #fafafa">
                    <div class="text-left d-grid mb-2">
                        <h6>Que vaga você procura?</h6>
                        <small style="color: #888">Exemplo: Desenvolvedor Python</small>
                    </div>

                    <form class="input-group" action="{% url 'search' %}">
                        <input
                            style="border-radius: 4px"
                            name="q"
                            data-filter="1"
                            class="form-control mr-sm-1"
                            type="search"
                            aria-label="Search"
                            placeholder="Pesquisar vaga de emprego"
                            required
                        />
                        <button class="btn btn-dark my-2 my-sm-0" style="border-radius: 4px; width: 8rem" type="submit">Pesquisar</button>
                    </form>
                </div>
            </div>
            {% endif %}

            <div class="row">
                <div class="col-md-10 mx-auto text-left mt-2">{% block content %}{% endblock %}</div>
            </div>
        </main>

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <!-- Script personalizado -->
        <script src="{% static 'main.js' %}"></script>

    </body>
</html>

core/templates/home_page.html
{% extends "base.html" %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}

{% if jobs %}
    <div class="content-section pt-4" style="padding-bottom: 0; border-radius: 6px; border: none; box-shadow: 0 1px 6px hsla(0, 0%, 4%, 0.1)">
        {% for job in jobs %}
            <article class="media pb-4 mb-4" style="border-bottom: 2px solid #ededed">
                <div style="width: 100%">
                    <span><a class="article-title" href="{% url 'job-detail' job.slug %}">{{ job.title }}</a></span>
                    <span class="text-muted mr-1" style="font-size: small">({{ job.created_date|custom_naturaltime }})</span><br />

                    <i class="bx bxs-building" style="font-size: small; margin-left: -2px"></i>
                    <span style="vertical-align: middle; font-size: small">{{ job.company }}</span><br />
                    <i class="bx bxs-map" style="font-size: small; margin-left: -2px"></i>
                    <span style="vertical-align: middle; font-size: small">{{ job.location }} </span><br />
                    <i class="bx bxs-briefcase" style="font-size: small; margin-left: -2px"></i>
                    <span style="vertical-align: middle; font-size: small">{{ job.get_hiring_type_display }}</span>
                    <span class="text-muted" style="font-size: small; vertical-align: middle">(Salário: {{ job.get_salary_display }})</span>
                </div>

                <div style="text-align: center; width: 8rem; margin-right: 2px">
                    {% if user.is_candidate == True or user.is_authenticated == False %}
                    <a class="btn btn-dark" style="margin-top: 4px; font-size: 14px; padding: 5px 8px 5px 9px" href="{% url 'request-job' job.slug %}" >Enviar Currículo</a>
                    {% endif %}
                </div>
            </article>
        {% endfor %}
    </div>
{% endif %}

{% endblock %}

core/templates/job_detail.html
{% extends "base.html" %} {% block content %}

<article class="media content-section">
    <div class="media-body">
        <legend class="mt-3"><span style="color: #343a40">{{ job.title }}</span></legend>
        <a style="font-size: 14px">Empresa: {{ job.company }}</a><br />
        <span style="font-size: 14px; color: #a2a2a2"
            ><i class="bx bxs-map" style="font-size: 12px; color: #a2a2a2"></i> {{ job.location }} </span
        ><br />
        <span style="font-size: 14px">{{ job.get_salary_display }} por mês</span>

        <div style="text-align: center; width: 8rem">
            {% if user.is_candidate == True or user.is_authenticated == False %}
            <a
                class="btn btn-dark"
                style="margin-top: 10px; font-size: 14px; padding: 5px 8px 5px 9px"
                href="{% url 'request-job' job.slug %}"
                >Enviar Currículo</a
            >
            <br />
            {% endif %}
        </div>

        <hr />

        <legend class="mt-3"><span style="color: #343a40">Dados da vaga</span></legend>
        <p class="mb-0" style="font-size: 14px; color: #a2a2a2; margin-top: -5px">Confira abaixo os pré-requisitos exigidos</p>
        <br />

        <div class="d-flex">
            <div>
                <i class="bx bxs-file mr-2"></i>Experiência<br />
                <span class="job-property ml-4"> {{ job.get_experience_display }} </span><br /><br />
            </div>

            <div style="margin-left: 4rem">
                <i class="bx bxs-badge-check mr-2"></i>Habilidades<br />
                <span class="job-property ml-4"> {{ job.skills_required }} </span><br /><br />
            </div>
        </div>

        <div class="d-flex" style="margin-bottom: -10px">
            <div>
                <i class="bx bxs-graduation mr-2"></i>Escolaridade<br />
                <span class="job-property ml-4"> {{ job.get_education_display }} </span><br /><br />
            </div>

            <div style="margin-left: 3rem">
                <i class="bx bxs-briefcase mr-2"></i>Tipo de vaga<br />
                <span class="job-property ml-4"> {{ job.get_hiring_type_display }} </span>
            </div>
        </div>

        <hr />

        <h6 class="mb-2 pt-2">Benefícios:</h6>
        <p style="font-size: 14px">{{ job.benefits }}</p>

        <h6 class="mt-4 mb-2">Descrição das atividades:</h6>
        <p style="font-size: 14px">{{ job.job_description }}</p>
    </div>
</article>

{% endblock %}

core/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

{% if messages %} 
    {% for message in messages %}
        <div class="col-md-9 mx-auto alert alert-{{ message.tags }}" style="text-align: center; border-radius: 6px">{{ message }}</div>
    {% endfor %}
{% endif %}

<div class="content-section col-md-9 mx-auto" style="border-radius: 6px">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 pb-2">Entrar</legend>
            {{ form.email|as_crispy_field }}

            <div>
                {{ form.password|as_crispy_field }}
                <i
                    style="position: absolute; top: 53.5%; right: 2rem; color: darkgray; cursor: pointer; font-size: 1.5rem"
                    id="#id_password"
                    class="bx bx-show-alt toggle-password"
                ></i>
            </div>
        </fieldset>
        <div class="form-group pb-2">
            <button class="btn btn-dark" style="width: 100%" type="submit">Entrar</button>
        </div>
    </form>
    <div class="border-top pt-3 pb-1" style="text-align: center">
        <small class="text-muted">
            Não possui cadastro?
            <a class="ml-1" href="{% url 'register' %}">Registrar-se</a>
        </small>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const passwordToggleButtons = document.querySelectorAll(".toggle-password");

        function togglePasswordVisibility(e) {
            const target = document.querySelector(e.currentTarget.getAttribute("id"));
            if (target.type === "password") {
                target.type = "text";
            } else {
                target.type = "password";
            }
        }

        passwordToggleButtons.forEach((button) => {
            button.addEventListener("click", togglePasswordVisibility);
        });
    });
</script>

{% endblock %}

core/templates/register.html
{% extends "base.html" %} 
{% load crispy_forms_filters %} 
{% load crispy_forms_tags %} 
{% block content %} 

{% if messages %} 
    {% for message in messages %}
        <div class="col-md-9 mx-auto alert alert-{{ message.tags }}" style="text-align: center; border-radius: 6px">{{ message }}</div>
    {% endfor %} 
{% endif %}

<div class="content-section col-md-9 mx-auto" style="border-radius: 6px">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 pb-2">Informações de cadastro</legend>
            {{ form.register_as|as_crispy_field }} {{ form.full_name|as_crispy_field }} {{ form.email|as_crispy_field }}

            <div>
                {{ form.password1|as_crispy_field }}
                <i
                    style="position: absolute; top: 58.5%; right: 2rem; color: darkgray; cursor: pointer; font-size: 1.5rem"
                    id="#id_password1"
                    class="bx bx-show-alt toggle-password"
                ></i>
            </div>

            <div>
                {{ form.password2|as_crispy_field }}
                <i
                    style="position: absolute; top: 72%; right: 2rem; color: darkgray; cursor: pointer; font-size: 1.5rem"
                    id="#id_password2"
                    class="bx bx-show-alt toggle-password"
                ></i>
            </div>
        </fieldset>
        <div class="form-group pb-2">
            <button class="btn btn-dark" style="width: 100%" type="submit">Registrar</button>
        </div>
    </form>
    <div class="border-top pt-3 pb-1" style="text-align: center">
        <small class="text-muted">
            Já possui cadastro?
            <a class="ml-1" href="{% url 'login' %}">Faça login</a>
        </small>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const registerAsField = document.getElementById("id_register_as");
        const fullNameLabel = document.querySelector("label[for='id_full_name']");
        const full_nameInput = document.getElementById("id_full_name");

        function updateFullNameLabel() {
            if (registerAsField.value === "candidate") {
                fullNameLabel.innerText = "Nome completo*";
                full_nameInput.placeholder = "Ex. José Uchôa";
            } else if (registerAsField.value === "company") {
                fullNameLabel.innerText = "Nome da empresa*";
                full_nameInput.placeholder = "Ex. Minha Empresa Ltda.";
            } else {
                fullNameLabel.innerText = "Nome completo*";
                full_nameInput.placeholder = "Ex. José Uchôa";
            }
        }

        // Atualize o label ao carregar a página e quando o campo register_as for alterado
        updateFullNameLabel();
        registerAsField.addEventListener("change", updateFullNameLabel);
    });

    document.addEventListener("DOMContentLoaded", function () {
        const passwordToggleButtons = document.querySelectorAll(".toggle-password");

        function togglePasswordVisibility(e) {
            const target = document.querySelector(e.currentTarget.getAttribute("id"));
            if (target.type === "password") {
                target.type = "text";
            } else {
                target.type = "password";
            }
        }

        passwordToggleButtons.forEach((button) => {
            button.addEventListener("click", togglePasswordVisibility);
        });
    });
</script>
{% endblock %}